# ReplicationController for the HelloWorld application
apiVersion: v1
kind: ReplicationController
metadata:
  name: helloworld
  namespace: {{NAMESPACE}} # Replace {{NAMESPACE}} with the actual namespace or remove it
  labels:
    app: helloworld
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - image: dockerhandson/spring-boot-mongo
        name: helloworld
        ports:
        - name: helloworld
          containerPort: 8080

---
# NodePort Service for HelloWorld application
apiVersion: v1
kind: Service
metadata:
  name: helloworld
  labels:
    app: helloworld
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: helloworld

---
# ReplicationController for MongoDB
apiVersion: v1
kind: ReplicationController
metadata:
  name: mongo-controller
  labels:
    app: mongo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - image: mongo
        name: mongo
        ports:
        - name: mongo
          containerPort: 27017
          hostPort: 27017
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
      volumes:
      - name: mongo-persistent-storage
        hostPath:
          path: /tmp/dbbackup

---
# ClusterIP Service for MongoDB
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  type: ClusterIP
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongo
