apiVersion: v1
kind: Secret
metadata:
  name: my-pull-secret
  namespace: devops-tools
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRo
IjogImNtRjVZWEpoY0hWMmJtVnJZWFJsYzJnNlpHTnJjbDl3WVhSZmR6QktaM1JOZWs5UFkxcE9i
VzUzWkhReWRqTTFNekU0TFVWTiIKCQl9Cgl9Cn0=
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld
  namespace: devops-tools
  labels:
    app: helloworld
spec:
  ports:
  - name: http
    port: 9094
    targetPort: 9094
  selector:
    app: helloworld
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  namespace: devops-tools
  labels:
    app: helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
        version: v1
    spec:
      containers:
      - name: helloworld
        ports:
        - containerPort: 9094
        image: rayarapuvnekatesh/tomcat:28
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 64Mi
      imagePullSecrets:
      - name: my-pull-secret
